version: "3.3"

services:
  jmeter:
    image: jmeter:latest
    build: docker/jmeter
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./tests:/home/jmeter/
    command: -n -t parallel_member_ingest.jmx -l report.jtl -e -o output/
    depends_on:
      ldes-server:
        condition: service_healthy

  ldes-server:
    image: ghcr.io/informatievlaanderen/ldes-server:20230620093538
    volumes:
      - ./config/ldes-server.config.yml:/application.yml:ro
    depends_on:
      - ldes-mongodb
    ports:
      - 8080:8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 2s
      retries: 5
    
  ldes-mongodb:
    image: mongo:${MONGODB_TAG:-latest}
    ports:
      - ${MONGODB_PORT:-27017}:27017
